version: '3.7'

services:

  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  redis_cache:
#    image: redis:7-alpine
#    ports:
#      - "6379:6379"


volumes:
  postgres_data:
